language: go

go:
    - "1.10"

go_import_path:
    - github.com/DanielSchuette/cloningPrimer

before_install:
    - go get -u honnef.co/go/tools/...
    - go get -u https://github.com/opennota/check
    - go get -u https://github.com/mvdan/interfacer
    - go get -u https://github.com/jgautheron/goconst
    - go get -u https://github.com/mdempsky/unconvert
    - go get -u https://github.com/securego/gosec
    - go get -u https://github.com/gordonklaus/ineffassign
    - go get -u https://github.com/alecthomas/gometalinter
    - go get -u github.com/DanielSchuette/cloningPrimer
