language: go

go:
    - "1.10"

go_import_path:
    - github.com/DanielSchuette/cloningPrimer

before_install:
    - go get -u honnef.co/go/tools/...
    - go get github.com/DanielSchuette/cloningPrimer
