language: go

go:
    - "1.10"

go_import_path:
    - github.com/DanielSchuette/cloningPrimer

before_install:
    - go get -u github.com/DanielSchuette/cloningPrimer

script:
    - go build -v
    - go test . -v -cover
