language: go

go:
    - "1.10.1"

before_install:
    - go get -u github.com/DanielSchuette/cloningPrimer
    - go get -u github.com/alecthomas/gometalinter
    - gometalinter --install

script:
    - go test . -v -cover
    - gometalinter . --disable=gocyclo
    - go build -v
